### ISSUE TITLE
A small issue

### ISSUE THREAD

**Issue by itrack** [techouse/select-auto-complete#1]
<img width="852" alt="screenshot 2018-11-27 at 23 37 11" src="https://user-images.githubusercontent.com/2368391/49113178-87630180-f29d-11e8-8ef7-e5cde466d421.png">

On version 1.1.9 it is not formatted well

**Comment by techouse** [comment]
Hmm, I tried the current version or this Nova component with the current `Laravel\Nova` version __1.2.0__ and it looks fine in Firefox, Google Chrome and Safari. Try clearing out the vendor directory an pulling in a fresh version maybe.
