### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by Milkhan** [techouse/select-auto-complete#11]
Thank you for the package! 
Is there any way to add a placeholder?

**Comment by techouse** [comment]
Hi @Milkhan 

Do you mean changing the default "Chose an option"? I don't think I've built this into the original package.

**Comment by Milkhan** [comment]
@techouse 
I see, if you are not going to add, maybe I can add it and send a pull request.

**Comment by techouse** [comment]
> @techouse
> I see, if you are not going to add, maybe I can add it and send a pull request.

By all means :)

**Comment by techouse** [comment]
Added in `v1.3.0`
