### ISSUE TITLE
Not working with latest releases

### ISSUE THREAD

**Issue by yehudahkay** [techouse/select-auto-complete#2]
Hi I've tried this with laravel 5.8 and nova 2.0, the field isn't generated correctly and display is incorrect

**Comment by techouse** [comment]
Thanx for reporting. I had yet no chance to test it on Laravel 5.8 with Nova 2.0. Will check it today, hopefully.

**Comment by techouse** [comment]
Hey, I just checked with vanilla install of Laravel 5.8.4 and Nova 2.0.0 and it works just fine. Can you elaborate on your problem a bit more?

**Comment by yehudahkay** [comment]
It fails in the index view with data like this

'{"role":"auditor"}' => 'Auditor',
            '{"role":"derm_auditor"}' => 'Dermatology Auditor',

**Comment by techouse** [comment]
Have you tried using simple keys instead of JSON strings?

**Comment by yehudahkay** [comment]
I dont know Im sorry, in this package he fixed for me
        "koss-shtukert/laravel-nova-select2-auto-complete": "^1.11",
