### ISSUE TITLE
N+1 Query Detected

### ISSUE THREAD

**Issue by shineirvin** [techouse/select-auto-complete#7]
```
    public function fields()
    {
        return [
            Select::make(__('Person'), 'person')
                  ->options(\App\Person::all()->mapWithKeys(function ($person) {
                      return [$person->id => $person->name];
                  }))
                  ->displayUsingLabels(),
     }
```

\App\Person::all() is causing N+1 Query, How do I prevent it ?

**Comment by techouse** [comment]
This is more of an ORM issue than a plugin issue. I guess you could cache the result and read from cache. Whenever the users table or any other list you'd like to use gets updated also update the cached version.
