### ISSUE TITLE
Outdated required() method

### ISSUE THREAD

**Issue by flexchar** [techouse/select-auto-complete#9]
Declaration of `Techouse\SelectAutoComplete\SelectAutoComplete::required()` should be compatible with `Laravel\Nova\Fields\Field::required($callback = true)`

`techouse/select-auto-complete/src/SelectAutoComplete.php:8`

**Comment by flexchar** [comment]
After brief investigation I'd just you don't really need extra `required()` method. Just remove the method and the feature (_required - OPTIONAL - Make the field required. Default is false._) and it will be fine! :)

**Comment by techouse** [comment]
Thanks for the PR! ❤️

**Comment by techouse** [comment]
Hmm, however now Vue single select won't get the `required` field prop. I'll check how to circumvent this.

**Comment by techouse** [comment]
Aha, you forgot to remove the required param on line 36. Fixed :)

**Comment by flexchar** [comment]
Thanks for fast fix, and yes that was a quick online edit example!
